package com.example.weatherforecastapp.ui.search

object CitiesObject {
    val listOfCities = listOf<String>(
        "Yerevan",
        "Canberra",
        "Vienna",
        "Baku",
        "Nassau",
        "Manama",
        "Dhaka",
        "Bridgetown",
        "Minsk",
        "Brussels",
        "Belmopan",
        "Thimphu",
        "Gaborone",
        "Brasilia",
        "Sofia",
        "Ouagadougou",
        "Yaounde",
        "Ottawa",
        "Praia",
        "Santiago",
        "Beijing",
        "Bogota",
        "Moroni",
        "Havana",
        "Nicosia",
        "Prague",
        "Copenhagen",
        "Djibouti",
        "Roseau",
        "Quito",
        "Cairo",
        "San Salvador",
        "London",
        "Malabo",
        "Asmara",
        "Tallinn",
        "Addis Ababa",
        "Helsinki",
        "Paris",
        "Libreville",
        "Banjul",
        "Tbilisi",
        "Berlin",
        "Accra",
        "Athens",
        "Conakry",
        "Bissau",
        "Georgetown",
        "Tegucigalpa",
        "Budapest",
        "Reykjavik",
        "Tehran",
        "Baghdad",
        "Dublin",
        "Jerusalem ",
        "Rome",
        "Kingston",
        "Tokyo",
        "Amman",
        "Astana",
        "Nairobi",
        "Tarawa",
    )
}